export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";

import * as h_ai_diagnostics from "@/lib/api-handlers/misc/ai-diagnostics";
import * as h_analytics_kpis from "@/lib/api-handlers/misc/analytics-kpis";
import * as h_analytics_patients from "@/lib/api-handlers/misc/analytics-patients";
import * as h_analytics_procedures from "@/lib/api-handlers/misc/analytics-procedures";
import * as h_analytics_reports from "@/lib/api-handlers/misc/analytics-reports";
import * as h_analytics_revenue from "@/lib/api-handlers/misc/analytics-revenue";
import * as h_billing from "@/lib/api-handlers/misc/billing";
import * as h_billing_id from "@/lib/api-handlers/misc/billing-id";
import * as h_billing_insurance_claims from "@/lib/api-handlers/misc/billing-insurance-claims";
import * as h_billing_insurance_claims_id_submit from "@/lib/api-handlers/misc/billing-insurance-claims-id-submit";
import * as h_billing_payments_process from "@/lib/api-handlers/misc/billing-payments-process";
import * as h_book from "@/lib/api-handlers/misc/book";
import * as h_book_services from "@/lib/api-handlers/misc/book-services";
import * as h_book_slots from "@/lib/api-handlers/misc/book-slots";
import * as h_book_verify_patient from "@/lib/api-handlers/misc/book-verify-patient";
import * as h_calendar_availability from "@/lib/api-handlers/misc/calendar-availability";
import * as h_calendar_conflicts from "@/lib/api-handlers/misc/calendar-conflicts";
import * as h_calendar_resources from "@/lib/api-handlers/misc/calendar-resources";
import * as h_change_password from "@/lib/api-handlers/misc/change-password";
import * as h_checkin_forms from "@/lib/api-handlers/misc/checkin-forms";
import * as h_checkin_forms_send_email from "@/lib/api-handlers/misc/checkin-forms-send-email";
import * as h_checkin_forms_token from "@/lib/api-handlers/misc/checkin-forms-token";
import * as h_clinic_hours from "@/lib/api-handlers/misc/clinic-hours";
import * as h_clinic_hours_defaults from "@/lib/api-handlers/misc/clinic-hours-defaults";
import * as h_clinic_hours_weekly from "@/lib/api-handlers/misc/clinic-hours-weekly";
import * as h_double_booking_weekly from "@/lib/api-handlers/misc/double-booking-weekly";
import * as h_double_booking_overrides from "@/lib/api-handlers/misc/double-booking-overrides";
import * as h_consent_token from "@/lib/api-handlers/misc/consent-token";
import * as h_custom_login from "@/lib/api-handlers/misc/custom-login";
import * as h_custom_session from "@/lib/api-handlers/misc/custom-session";
import * as h_dashboard_stats from "@/lib/api-handlers/misc/dashboard-stats";
import * as h_dental_procedures from "@/lib/api-handlers/misc/dental-procedures";
import * as h_dental_procedures_id from "@/lib/api-handlers/misc/dental-procedures-id";
import * as h_dental_records from "@/lib/api-handlers/misc/dental-records";
import * as h_dental_records_id from "@/lib/api-handlers/misc/dental-records-id";
import * as h_dental_records_id_teeth from "@/lib/api-handlers/misc/dental-records-id-teeth";
import * as h_dentists from "@/lib/api-handlers/misc/dentists";
import * as h_files_download from "@/lib/api-handlers/misc/files-download";
import * as h_files_upload from "@/lib/api-handlers/misc/files-upload";
import * as h_form_templates from "@/lib/api-handlers/misc/form-templates";
import * as h_form_templates_id from "@/lib/api-handlers/misc/form-templates-id";
import * as h_form_templates_id_new_version from "@/lib/api-handlers/misc/form-templates-id-new-version";
import * as h_forms from "@/lib/api-handlers/misc/forms";
import * as h_forms_id from "@/lib/api-handlers/misc/forms-id";
import * as h_forms_id_download from "@/lib/api-handlers/misc/forms-id-download";
import * as h_forms_templates from "@/lib/api-handlers/misc/forms-templates";
import * as h_intake from "@/lib/api-handlers/misc/intake";
import * as h_intake_token from "@/lib/api-handlers/misc/intake-token";
import * as h_inventory from "@/lib/api-handlers/misc/inventory";
import * as h_inventory_auto_deduction from "@/lib/api-handlers/misc/inventory-auto-deduction";
import * as h_inventory_id from "@/lib/api-handlers/misc/inventory-id";
import * as h_inventory_search from "@/lib/api-handlers/misc/inventory-search";
import * as h_inventory_transactions from "@/lib/api-handlers/misc/inventory-transactions";
import * as h_announcements_public from "@/lib/api-handlers/misc/announcements-public";
import * as h_image_proxy from "@/lib/api-handlers/misc/image-proxy";
import * as h_notifications from "@/lib/api-handlers/misc/notifications";
import * as h_notifications_id from "@/lib/api-handlers/misc/notifications-id";
import * as h_package_templates from "@/lib/api-handlers/misc/package-templates";
import * as h_package_templates_id from "@/lib/api-handlers/misc/package-templates-id";
import * as h_reports_generate from "@/lib/api-handlers/misc/reports-generate";
import * as h_reports_v2_export from "@/lib/api-handlers/misc/reports-v2-export";
import * as h_reports_v2_preview from "@/lib/api-handlers/misc/reports-v2-preview";
import * as h_settings from "@/lib/api-handlers/misc/settings";
import * as h_settings_id from "@/lib/api-handlers/misc/settings-id";
import * as h_settings_public from "@/lib/api-handlers/misc/settings-public";
import * as h_consent_template from "@/lib/api-handlers/misc/consent-template";
import * as h_signup from "@/lib/api-handlers/misc/signup";
import * as h_staff from "@/lib/api-handlers/misc/staff";
import * as h_suppliers from "@/lib/api-handlers/misc/suppliers";
import * as h_today_flow from "@/lib/api-handlers/misc/today-flow";
import * as h_treatment_plans from "@/lib/api-handlers/misc/treatment-plans";
import * as h_treatment_slash_plans from "@/lib/api-handlers/misc/treatment-slash-plans";
import * as h_treatments from "@/lib/api-handlers/misc/treatments";
import * as h_treatments_id from "@/lib/api-handlers/misc/treatments-id";
import * as h_users from "@/lib/api-handlers/misc/users";
import * as h_users_id from "@/lib/api-handlers/misc/users-id";
import * as h_users_profile_picture from "@/lib/api-handlers/misc/users-profile-picture";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type HandlerFn = (req: NextRequest, ctx: any) => any;
type HandlerModule = Record<string, HandlerFn>;

function matchRoute(segments: string[]): { handler: HandlerModule; params: Record<string, string> } | null {
  if (segments.length === 5 && segments[0] === "billing" && segments[1] === "insurance" && segments[2] === "claims" && segments[4] === "submit") return { handler: h_billing_insurance_claims_id_submit as unknown as HandlerModule, params: { id: segments[3] } };
  if (segments.length === 3 && segments[0] === "billing" && segments[1] === "insurance" && segments[2] === "claims") return { handler: h_billing_insurance_claims as unknown as HandlerModule, params: {} };
  if (segments.length === 3 && segments[0] === "billing" && segments[1] === "payments" && segments[2] === "process") return { handler: h_billing_payments_process as unknown as HandlerModule, params: {} };
  if (segments.length === 3 && segments[0] === "reports" && segments[1] === "v2" && segments[2] === "export") return { handler: h_reports_v2_export as unknown as HandlerModule, params: {} };
  if (segments.length === 3 && segments[0] === "reports" && segments[1] === "v2" && segments[2] === "preview") return { handler: h_reports_v2_preview as unknown as HandlerModule, params: {} };
  if (segments.length === 3 && segments[0] === "dental-records" && segments[2] === "teeth") return { handler: h_dental_records_id_teeth as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 3 && segments[0] === "form-templates" && segments[2] === "new-version") return { handler: h_form_templates_id_new_version as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 3 && segments[0] === "forms" && segments[2] === "download") return { handler: h_forms_id_download as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "analytics" && segments[1] === "kpis") return { handler: h_analytics_kpis as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "analytics" && segments[1] === "patients") return { handler: h_analytics_patients as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "analytics" && segments[1] === "procedures") return { handler: h_analytics_procedures as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "analytics" && segments[1] === "reports") return { handler: h_analytics_reports as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "analytics" && segments[1] === "revenue") return { handler: h_analytics_revenue as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "book" && segments[1] === "services") return { handler: h_book_services as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "book" && segments[1] === "slots") return { handler: h_book_slots as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "book" && segments[1] === "verify-patient") return { handler: h_book_verify_patient as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "calendar" && segments[1] === "availability") return { handler: h_calendar_availability as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "calendar" && segments[1] === "conflicts") return { handler: h_calendar_conflicts as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "calendar" && segments[1] === "resources") return { handler: h_calendar_resources as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "checkin-forms" && segments[1] === "send-email") return { handler: h_checkin_forms_send_email as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "clinic-hours" && segments[1] === "defaults") return { handler: h_clinic_hours_defaults as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "clinic-hours" && segments[1] === "weekly") return { handler: h_clinic_hours_weekly as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "double-booking" && segments[1] === "weekly") return { handler: h_double_booking_weekly as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "double-booking" && segments[1] === "overrides") return { handler: h_double_booking_overrides as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "dashboard" && segments[1] === "stats") return { handler: h_dashboard_stats as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "files" && segments[1] === "download") return { handler: h_files_download as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "files" && segments[1] === "upload") return { handler: h_files_upload as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "forms" && segments[1] === "templates") return { handler: h_forms_templates as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "inventory" && segments[1] === "auto-deduction") return { handler: h_inventory_auto_deduction as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "inventory" && segments[1] === "search") return { handler: h_inventory_search as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "inventory" && segments[1] === "transactions") return { handler: h_inventory_transactions as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "reports" && segments[1] === "generate") return { handler: h_reports_generate as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "treatment" && segments[1] === "plans") return { handler: h_treatment_slash_plans as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "users" && segments[1] === "profile-picture") return { handler: h_users_profile_picture as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "billing") return { handler: h_billing_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "checkin-forms") return { handler: h_checkin_forms_token as unknown as HandlerModule, params: { token: segments[1] } };
  if (segments.length === 2 && segments[0] === "consent") return { handler: h_consent_token as unknown as HandlerModule, params: { token: segments[1] } };
  if (segments.length === 2 && segments[0] === "dental-procedures") return { handler: h_dental_procedures_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "dental-records") return { handler: h_dental_records_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "form-templates") return { handler: h_form_templates_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "forms") return { handler: h_forms_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "intake") return { handler: h_intake_token as unknown as HandlerModule, params: { token: segments[1] } };
  if (segments.length === 2 && segments[0] === "inventory") return { handler: h_inventory_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "notifications") return { handler: h_notifications_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "package-templates") return { handler: h_package_templates_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "settings" && segments[1] === "public") return { handler: h_settings_public as unknown as HandlerModule, params: {} };
  if (segments.length === 2 && segments[0] === "settings") return { handler: h_settings_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "treatments") return { handler: h_treatments_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 2 && segments[0] === "users") return { handler: h_users_id as unknown as HandlerModule, params: { id: segments[1] } };
  if (segments.length === 1 && segments[0] === "ai-diagnostics") return { handler: h_ai_diagnostics as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "billing") return { handler: h_billing as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "book") return { handler: h_book as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "change-password") return { handler: h_change_password as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "checkin-forms") return { handler: h_checkin_forms as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "clinic-hours") return { handler: h_clinic_hours as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "consent-template") return { handler: h_consent_template as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "custom-login") return { handler: h_custom_login as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "custom-session") return { handler: h_custom_session as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "dental-procedures") return { handler: h_dental_procedures as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "dental-records") return { handler: h_dental_records as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "dentists") return { handler: h_dentists as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "form-templates") return { handler: h_form_templates as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "announcements") return { handler: h_announcements_public as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "image-proxy") return { handler: h_image_proxy as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "forms") return { handler: h_forms as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "intake") return { handler: h_intake as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "inventory") return { handler: h_inventory as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "notifications") return { handler: h_notifications as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "package-templates") return { handler: h_package_templates as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "settings") return { handler: h_settings as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "signup") return { handler: h_signup as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "staff") return { handler: h_staff as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "suppliers") return { handler: h_suppliers as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "today-flow") return { handler: h_today_flow as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "treatment-plans") return { handler: h_treatment_plans as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "treatments") return { handler: h_treatments as unknown as HandlerModule, params: {} };
  if (segments.length === 1 && segments[0] === "users") return { handler: h_users as unknown as HandlerModule, params: {} };
  return null;
}

async function handle(req: NextRequest, { params: rawParams }: { params: Promise<{ path?: string[] }> }) {
  const resolved = await rawParams;
  const segments = resolved?.path || [];
  const matched = matchRoute(segments);
  if (!matched) return NextResponse.json({ error: "Not found" }, { status: 404 });
  const method = req.method;
  const fn = matched.handler[method];
  if (!fn) return NextResponse.json({ error: "Method not allowed" }, { status: 405 });
  return fn(req, { params: matched.params });
}

export const DELETE = handle;
export const GET = handle;
export const PATCH = handle;
export const POST = handle;
export const PUT = handle;